---

- name: check if www dir exists {{ instance.name }}
  stat:
    path: /home/www-data/{{ instance.name }}/www
  register: www_file

- name: Create home directory for instance {{ instance.name }}
  file:
    path: /home/www-data/{{ instance.name }}/www
    state: directory
    owner: www-data
    group: root
    mode: '0755'

- name: Unarchive a file that needs to be downloaded (added in 2.0)
  unarchive:
    src: https://wordpress.org/latest.tar.gz
    dest: /home/www-data/{{ instance.name }}/www
    remote_src: yes
  when: not www_file.stat.exists

- name: change owner of wordpress instance {{ instance.name }}
  file: 
    dest: /home/www-data/{{ instance.name }}/www
    owner: www-data
    group: root
    recurse: yes

- name: check if config file exists {{ instance.name }}
  stat:
    path: /root/.my.cnf-{{ instance.db_user }}
  register: pass_file

- name: Get wp pass
  shell: |
      cat /root/.my.cnf-{{ instance.db_user }}
  register: WORDPRESS_DB_PASSWORD
  changed_when: false
  when: pass_file.stat.exists

- name: wordpress config file
  template:
    src: etc/wordpress/config.php.j2
    dest: /home/www-data/{{ instance.name }}/www/wordpress/wp-config.php
    owner: root
    group: root
    mode: '0644'

