---

- name: packages role
  include_role:
    name: packages
  vars:
    PKGS_LIST: "{{ V2RAY_PKGS_LIST }}"

- name: Create directory if it does not exist
  file:
    path: /opt/v2ray_toolbox/
    state: directory
    mode: '0755'

- name: Copy v2ray_toolbox
  copy:
    src: opt/v2ray_toolbox/{{ item }}
    dest: /opt/v2ray_toolbox/{{ item }}
    owner: root
    group: root
  with_items:
    - v2ray.sh

- name: nginx config for v2ray
  template:
    src: etc/nginx/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'

- name: configuring nginx instances
  include_tasks: nginx.yml
  loop: "{{ NGINX_INSTANCES }}"
  loop_control:
    loop_var: instance

- name: configuring instances
  include_tasks: instances.yml
  loop: "{{ V2RAY_INSTANCES }}"
  loop_control:
    loop_var: instance

- name: generate vmess url
  shell: |
    bash /opt/v2ray_toolbox/v2ray.sh "{{ V2RAY_CFG_DOMAIN }}" "{{ V2RAY_CFG_PREDOMAIN }}" "{{ MAIN_DOMAIN }}"
  changed_when: false
