---

- name: nginx config for {{ instance.domain }}
  template:
    src: etc/nginx/specific-conf.d/specific.conf.j2
    dest: /etc/nginx/specific-conf.d/{{ instance.domain }}-specific.conf
    owner: root
    group: root
    mode: '0644'

- name: nginx config for {{ instance.domain }}
  template:
    src: etc/nginx/conf.d/nginx.conf.j2
    dest: /etc/nginx/conf.d/{{ instance.domain }}.conf
    owner: root
    group: root
    mode: '0644'
